## Reading in all the functions in the R directory 

source("R/amr.R")
source("R/animal_health_public_sector.R")
source("R/arable_land.R")
source("R/cfe_allocations.R")
source("R/combined_data_sheet.R")
source("R/fao_import_export.R")
source("R/fao_livestock.R")
source("R/fisheries_production.R")
source("R/jee.R")
source("R/malaria_cases.R")
source("R/medical_doctors.R")
source("R/population.R")
source("R/promed.R")
source("R/rabies_deaths.R")
source("R/rabies_management.R")
source("R/spar.R")
source("R/taenia_solium.R")
source("R/terrestrial_protected_area.R")
source("R/vet_capacity.R")
source("R/wash_hygiene.R")
source("R/wash_sanitation.R")
source("R/wash_water.R")
source("R/yellow_fever.R")

